version: "2.2"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama-devoxx
    volumes:
      - /home/benjamin/dev/perso/docker/ollama:/root/.ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
